### PR TITLE
fix(integrations): Use a home-grown findById for our model

### LINKED ISSUE #631: Cannot add additional filter step
@rhuss commented on [Fri Jul 21 2017](https://github.com/syndesisio/syndesis-rest/issues/452)

When pussing "+ Add another rule" the following JavaScript exception occurs. This happens when creating a new filter step or editing an already existing filter step

image

### LINKED ISSUE #654: Basic Filter: Changes persisted in-memory prior to saving
Important bug related to persistence in the API vs in-memory store, as pointed out in issue #623.

How to reproduce:
1. Make changes to an integration's basic filter rule.
2. Do not save changes to the integration.
3. Begin to create a new integration and add the basic filter as a step.
4. Fields will be pre-populated (or rule rows appended will appear as well) with values from the prior integration's basic filter step.

This is a brand new integration, attempting to add a basic filter step, without ever having saved:

screenshot 2017-07-25 10 43 00

### PR DESCRIPTION
**Pull request by gashcrumb**
Switch to a function that returns the model (fixes #654) and also use a home-grown findById function
to locate objects in the filter model.

fixes #631 and fixes #654

### CODE REVIEW

File: src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.ts [hunk 1]
```diff
@@ -66,10 +66,10 @@ export class BasicFilterComponent implements OnInit {
     this.formGroup = this.formService.createFormGroup(this.basicFilterModel);
 
     this.predicateControl = this.formGroup.get('filterSettingsGroup').get('predicate') as FormControl;
-    this.predicateModel = this.formService.findById('predicate', this.basicFilterModel) as DynamicInputModel;
+    this.predicateModel = findById('predicate', this.basicFilterModel) as DynamicInputModel;
```
Comment (kahboom) [inline src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.ts]: Aha the darn formService..
